# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1 # We must use 2.1 to make use of orbs.
orbs: # specify all orbs you want to use.
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: laravel-sns # The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
          deployment-group: master # The name of a new deployment group for the specified application.
          service-role-arn: arn:aws:iam::831132817655:user/laravel-sns-deploy # The service role for a deployment group.
          bundle-bucket: laravel-sns-code # The s3 bucket where an application revision will be stored.
          bundle-key: code # A key under the s3 bucket where an application revision will be stored.
          filters:
            branches:
              only: master
